### ISSUE TITLE
view the tx calldata

### ISSUE THREAD

**Issue by huahuayu** [impersonator-eth/impersonator#18]
Hi Apoorv, there's a scenario I often used in metamask, that is press the confirm button in dapp to invoke metamask, but I just want to check the contract address and calldata.

Since impresonator-eth is for impresonator the address, but it can only view the data in dapp front page, I can't read the calldata after I click send tx button.

**Comment by apoorvlathey** [comment]
Hey the calldata is shown by expanding the "eth_sendTransactions" table:
![image](https://github.com/impersonator-eth/impersonator/assets/20395316/317779dd-8603-4529-9c8e-b60705ecd0c9)

**Comment by huahuayu** [comment]
It's really cool! 
But it only works on [impersonator.xyz](https://impersonator.xyz/), it's not in the plugin, the limitation is you can only use walletconnect.

The plugin take over metamask, which is more widely used.

**Comment by apoorvlathey** [comment]
Ohh now I get it. I'll make sure to add it to the browser extension: https://github.com/impersonator-eth/impersonator-extension
