### ISSUE TITLE
WalletConnect 2.0

### ISSUE THREAD

**Issue by lochie** [impersonator-eth/impersonator#9]
Just a heads up that as of March 1st [WalletConnect 1.0 will be sunset](https://medium.com/walletconnect/how-to-prepare-for-the-walletconnect-v1-0-shutdown-1a954da1dbff), so if you want this service to continue working you'll need to update soon.

**Comment by lochie** [comment]
This date has been [postponed until June 28th](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595).

**Comment by apoorvlathey** [comment]
Thanks for updating! I have started the work on integrating WC v2

**Comment by apoorvlathey** [comment]
Thank you @cpecorari, I referenced some of the changes you made and finally added support for WalletConnect V2, while also retaining legacy V1.
Merged the PR #11
